### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by lebechec** [eprintsug/coversheets-latex#3]
Hi,

i am trying to install this plugin for my repository (3.3.12). Everything looks okay. I can see the preview in the administration. (magnifying glass) But when I try to view the result on a notice, I get this error message:
"EPrints System Error
Attempt to get value from not existent field: eprint/has_original_cover."

Same thing of course, if I try to apply, via the interface or command line.

I don't see in your scripts a method to create this field ("push"). Can you help me? 

Thank you!

Jean-Marie

**Comment by mpbraendle** [comment]
Hmm. That is probably a field definition from the previous Coversheet implementation we had before we went to LaTeX.

Here it is

\# field added to mark EPrints with an original coversheet
          {
            'name' => 'has_original_cover',
            'type' => 'boolean',
          },

Probably, in this implementation, you could remove in the code all references to it.
That is, in cfg.d/z_coversheet.pl and cfg.d/z_coversheet_trigger.pl

**Comment by jesusbagpuss** [comment]
Or, the two calls to this could use the exists_and_set method - allowing a repository to add the 'has_original_cover' field/checks if needed?

```perl
#in cfg/cfg.d/z_coversheet_trigger.pl
return EP_TRIGGER_OK if $eprint->exists_and_set( "has_original_cover" ) && $eprint->get_value( "has_original_cover" ) eq "TRUE";
```
and
```perl
#in cfg/cfg.d/z_coversheet.pl
return 0 if $eprint->exists_and_set( "has_original_cover" ) && $eprint->value( "has_original_cover" ) eq "TRUE";
```

**Comment by lebechec** [comment]
Yes, thank you, that seems to be the source of the problem. I commented the following lines:

        #my $has_original_cover = $eprint->get_value( "has_original_cover" );
        #return EP_TRIGGER_OK if $has_original_cover && $has_original_cover eq "TRUE";

in z_coversheet_trigger.pl

and 
       #my $has_original_cover = $eprint->get_value( "has_original_cover" );
        #return 0 if $has_original_cover && $has_original_cover eq "TRUE";
in 
z_coversheet.pl
